# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Space Impact iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Space Impact iOS

end

target 'Space Impact watchOS App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Space Impact watchOS App

end

target 'Space Impact watchOS App Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Space Impact watchOS App Extension

end
